-- Categories and items as they were in the live database on 2026-10-10 (61 items, 11 categories).
-- Runs after the migrations on `supabase db reset`; safe to re-run (upserts).
-- Not included: profiles, confirmed days, activity, archives, push subscriptions and the
-- purchases_private.push_config row (VAPID keys + hook secret), which must never be committed.

insert into public.purchases_categories (id, name, sub, hue, sort, shop_sort) values
  (1, 'Grains & Bakery', null, '#E9A93B', 1, 7),
  (2, 'Oils, Sauces & Condiments', null, '#D9B44A', 2, 3),
  (3, 'Spices', null, '#D8683F', 3, 8),
  (4, 'Sweeteners & Spreads', null, '#C98A3A', 4, 2),
  (5, 'Beverages', null, '#B0704F', 5, 1),
  (6, 'Cleaning & Laundry', null, '#4FB3C9', 6, 5),
  (7, 'Paper & Bags', null, '#7C9CE0', 7, 6),
  (8, 'Personal Care', null, '#A68BE0', 8, 4),
  (9, 'Meat & Poultry', 'Chilled', '#E0625A', 9, 10),
  (10, 'Dairy, Eggs & Deli', 'Chilled', '#E6D3A3', 10, 9),
  (11, 'Frozen', 'Keep cold', '#8FD3E8', 11, 11)
on conflict (id) do update set name = excluded.name, sub = excluded.sub, hue = excluded.hue,
  sort = excluded.sort, shop_sort = excluded.shop_sort;

insert into public.purchases_items (id, name, category_id, default_unit, sort) values
  ('white-rice', 'White rice', 1, 'kg', 1),
  ('basmati-rice', 'Basmati rice', 1, 'kg', 2),
  ('vermicelli', 'Vermicelli', 1, 'pack', 3),
  ('flour', 'Flour', 1, 'kg', 4),
  ('starch', 'Starch', 1, 'pack', 5),
  ('toast', 'Toast', 1, 'pack', 6),
  ('cooking-oil', 'Cooking oil', 2, 'bottle', 7),
  ('olive-oil', 'Olive oil', 2, 'bottle', 8),
  ('vinegar', 'Vinegar', 2, 'bottle', 9),
  ('tomato-paste', 'Tomato paste', 2, 'can', 10),
  ('mustard', 'Mustard', 2, 'jar', 11),
  ('mayonnaise', 'Mayonnaise', 2, 'jar', 12),
  ('salt', 'Salt', 3, 'pack', 13),
  ('black-pepper', 'Black pepper', 3, 'pack', 14),
  ('paprika', 'Paprika', 3, 'pack', 15),
  ('smoked-paprika', 'Smoked paprika', 3, 'pack', 16),
  ('onion-powder', 'Onion powder', 3, 'pack', 17),
  ('garlic-powder', 'Garlic powder', 3, 'pack', 18),
  ('other-cooking-spices', 'Other cooking spices', 3, 'pack', 19),
  ('white-honey', 'White honey', 4, 'jar', 20),
  ('black-honey', 'Black honey', 4, 'jar', 21),
  ('tahini', 'Tahini', 4, 'jar', 22),
  ('plain-turkish-coffee', 'Plain Turkish coffee', 5, 'pack', 23),
  ('roasted-turkish-coffee', 'Roasted Turkish coffee', 5, 'pack', 24),
  ('nescafe', 'Nescafé', 5, 'jar', 25),
  ('loose-tea', 'Loose Tea', 5, 'pack', 26),
  ('packet-tea', 'Packet Tea', 5, 'box', 27),
  ('pepsi', 'Pepsi', 5, 'can', 28),
  ('dish-soap', 'Dish soap', 6, 'bottle', 29),
  ('clothes-washing-gel', 'Clothes washing gel', 6, 'bottle', 30),
  ('black-clothes-washing-gel', 'Black clothes washing gel', 6, 'bottle', 31),
  ('toilet-paper', 'Toilet paper', 7, 'roll', 32),
  ('table-tissue', 'Table tissue', 7, 'box', 33),
  ('kitchen-tissue', 'Kitchen tissue', 7, 'roll', 34),
  ('refrigerator-bags', 'Refrigerator bags', 7, 'roll', 35),
  ('rubbish-bags', 'Rubbish bags', 7, 'roll', 36),
  ('mattress-roll', 'Mattress Roll', 7, 'roll', 37),
  ('toothpaste', 'Toothpaste', 8, 'pcs', 38),
  ('always', 'Pads', 8, 'pack', 39),
  ('beef-tenderloin', 'Beef tenderloin', 9, 'kg', 40),
  ('minced-meat', 'Minced meat', 9, 'kg', 41),
  ('stew-meat-for-vegetables', 'Stew meat (for vegetables)', 9, 'kg', 42),
  ('chicken-breast', 'Chicken breast', 9, 'kg', 43),
  ('whole-chicken', 'Whole chicken', 9, 'pcs', 44),
  ('full-cream-milk', 'Full cream milk', 10, 'L', 45),
  ('skimmed-milk', 'Skimmed milk', 10, 'L', 46),
  ('yogurt', 'Yogurt', 10, 'pcs', 47),
  ('cooking-cream', 'Cooking cream', 10, 'pack', 48),
  ('mozzarella', 'Mozzarella', 10, 'kg', 49),
  ('roumi-cheese', 'Roumi cheese', 10, 'kg', 50),
  ('luncheon', 'Luncheon', 10, 'g', 51),
  ('eggs', 'Eggs', 10, 'tray', 52),
  ('frozen-vegetables', 'Frozen vegetables', 11, 'bag', 53),
  ('clorox-kitchen-cleaner-spray', 'Clorox kitchen cleaner spray', 6, 'bottle', 54),
  ('orzo-pasta', 'Orzo pasta', 1, 'g', 55),
  ('sambousa', 'Sambousa', 11, 'pack', 56),
  ('cheddar-chesse', 'Cheddar chesse', 10, 'kg', 57),
  ('cumin', 'Cumin', 3, 'g', 58),
  ('bay-leaves', 'Bay leaves', 3, 'g', 59),
  ('coriander', 'Coriander', 3, 'g', 60),
  ('butter', 'Butter', 10, 'pack', 61)
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id,
  default_unit = excluded.default_unit, sort = excluded.sort;
